sudo: required

language: node_js

node_js: 8

env:
  - CXX=g++-4.8

branches:
  only:
    - master

addons:
  hosts:
  - localhost

before_script:
- npm install -g grunt-cli

script:
- grunt coverage

